### PR TITLE
Added icons for CSS preprocessors - Less, Stylus

### PR DESCRIPTION
**Pull request by tomexx**
+ updated devicons font file
+ removed trailing whitespace according to .editorconfig

### CODE REVIEW

**Comment by Alhadis** [comment]
Could you include the `selection.json` file provided by IcoMoon, please? This part is vital, because it means future additions will overwrite your ones.

You'll also need to pull the latest changes from the master branch into yours, as there're conflicts that need resolving.

Lastly, are the icons you're adding different to the ones included in [Devicons](http://vorillaz.github.io/devicons/#/cheat)? Because that font already has icons for Sass and Less, and they can be specified in your stylesheet. I'd rather not add duplicate icons, because I'd prefer to keep the font's filesize as minimal as possible.

**Comment by tomexx** [comment]
Well, I used the existing icons from Devicons. Ok I will resolve the conflicts ASAP

**Comment by Alhadis** [comment]
Ah, actually, if you're duplicating icons, you needn't bother...

As I said, I'd rather not duplicate icons.

**Comment by tomexx** [comment]
I just updated Devicons font file with the latest one and I used Less and Stylus icon for .less and .styl filetypes instead of generic CSS icon. I will push a conflict-free commit ASAP.

**Comment by Alhadis** [comment]
OH! Sorry, I completely misread this PR, I thought you added icons to `file-icons.woff`. My fault.

Why did the devicons font need to be updated?

**Comment by tomexx** [comment]
Well, it might not be required now but I think we should ideally use always the latest version.

**Comment by Alhadis** [comment]
Well, there's an [optimised version of Devicons](https://github.com/Alhadis/DevOpicons) that's due to be included in v2.0.0 of the package. So the upgrade will happen anyway. =)

FYI, v2.0.0 is waiting on Atom to merge some [needed fixes upstream](https://github.com/DanBrooker/file-icons/issues/359). So we're waiting on them.

**Comment by tomexx** [comment]
Ok, I rebased onto the current master.

**Comment by Alhadis** [comment]
\*wince\* Christ, I'd love to headbutt whoever designed Less's logo. It's such a crap design.

Okay, first thing's first: I can tell this addition's not going to go down well with users:

Figure 1

This was *after* I tweaked the icon's CSS to make it look better in the tree-view:

Figure 2

**Comment by tomexx** [comment]
Looks cool now I think.

**Comment by Alhadis** [comment]
It's too wide when compared with other icons:

screen shot 2016-05-24 at 12 00 35 am

If I shrink it smaller, details will be lost and it'll just look like a strip of fuzz. As for the tab-icons, they look terrible...

I'm sorry man, I can tell there's a reason this icon was never added for Less files. Stylus isn't as bad, but it *is* faint. I suppose we can still use that.

**Comment by tomexx** [comment]
NP, it's up to you. Regarding Stylus, there is already a new version of the logo available. A few days ago I created a PR to Devicons repo reflecting the design change. The new version of the logo will look better in file-icons too.

**Comment by Alhadis** [comment]
Thank God. You're right, it will look better. I'll look into adding that to the custom icons set.

I'll revert this commit for now, sorry for this.

**Comment by Alhadis** [comment]
Look on the bright side: maybe Less's maintainers will notice Stylus's logo change and follow suit. =)

**Pull request merged**
