### PR TITLE
add .svg files support

### LINKED ISSUE #196: There is no icon for SVG
Here is svg logo: https://github.com/gilbarbara/logos/blob/master/logos/svg.svg

### PR DESCRIPTION
**Pull request by sanusart**
- add .svg files support via Icomoon icon

Closes #196

### CODE REVIEW

**Comment by nkt** [comment]
Hm. Why it doesn't work fine:

/cc @sanusart @DanBrooker

**Comment by DanBrooker** [comment]
The font file mustn't have that icon

cc @sanusart

**Comment by sanusart** [comment]
@DanBrooker the icon exists in icomoon-free https://github.com/Keyamoon/IcoMoon-Free/blob/master/Font/demo-files/demo.css#L1630
I made the change while viewing the `/examples` folder with new file `svg.svg` created and it seemed fine:
image

I'll check what might be the issue and update.

**Comment by nkt** [comment]
I guess you should also make it smaller due your screenshot.

**Comment by sanusart** [comment]
@nkt I don't wan't to change it on the icon as it is globally set on this icomoon font [here](https://github.com/sanusart/file-icons/blob/836ece8ad86c58f1ef09a0b3289112d3942b5c9a/styles/icons.less#L66)

Also there is #27 so I guess it is the desired size.

**Comment by sanusart** [comment]
OK, I removed all dev files that might conflict with it, but still the icon loads. @nkt can you disable/enable the package? Also please see if the font file is loaded:
image

**Comment by sanusart** [comment]
So it appears I have two icomoon.woff files loaded by different packages :open_mouth:, file-icons and one from [tool-bar](https://github.com/suda/tool-bar/blob/master/iconsets/icomoon/icomoon.woff). The later appear to be more up to date so it has that icon.

@DanBrooker What's more appropriate? Should I update the font or change the icon?

**Comment by DanBrooker** [comment]
Just update the font

**Pull request merged**
