### PR TITLE
Add hamlc extension for haml icon

### PR DESCRIPTION
**Pull request by alex88**
For people using https://github.com/netzpirat/haml-coffee or https://github.com/emilioforrer/haml_coffee_assets to write haml files in coffeescript templates (used with angular etc)

### CODE REVIEW

**Comment by Alhadis** [comment]
Could you change the colour?

At the moment, both `.haml` and `.hamlc` share the same colour-swatch, making it impossible to distinguish between them without checking their extension.

**Comment by alex88** [comment]
Why a different color? Isn't this the same case as an .htm/.html extension?

**Comment by Alhadis** [comment]
Not really. HTM and HTML refer to the same thing. Whereas languages like HAML and HAMLC are essentially two different languages: one for ordinary HAML, and another for a coffee-script-fuelled one

**Comment by alex88** [comment]
Oh sure, what about `medium-maroon` as coffeescript?

**Comment by Alhadis** [comment]
Sounds good to me! :)

**Comment by Alhadis** [comment]
@alex88 Once you've added the change, I'll cut a new release. =)

**Comment by alex88** [comment]
Sorry for the delay, doing that right now so you can release ;)

**Comment by alex88** [comment]
Done ;)

**Comment by Alhadis** [comment]
Ah ace, thanks!

Sorry, my turn to apologise about delays, heh.

**Pull request merged**
