### PR TITLE
modify color depending on background color of tree view

### PR DESCRIPTION
**Pull request by hgGeorg**
Suggestion for #168:

Colors are modified based on `@tree-view-background-color`:
Existing colors are 'darkened' by multiplying with `#666`, then saturated.
The contrast function is used to choose between the two alternatives.
The original darken and lighten function are applied after other modifications, as they could cause wacky behaviors when used earlier.

The method of modification (multiply then saturate) was determined by trial. If anyone has a better solution, let me know and I'll change it.

### CODE REVIEW

**Comment by hgGeorg** [comment]
I have an alternative solution ready, with which the use can opt in for darker icons. But it's kinda ugly and probably less maintainable because I'm not very experienced with less.

**Comment by DanBrooker** [comment]
Thanks for giving that a go, I'm not sure it's any better for light themes, many of the icons are still too bright.

What do you think @ahmadseleem and @roman01la?

**Comment by ahmadseleem** [comment]
So far better except for:
- js
- bower
- haml

Seems the yellows are to light...
Just change all the yellows I guess!
How about that: #F1980A

**Comment by ahmadseleem** [comment]
Or that: #E0B23C

**Comment by hgGeorg** [comment]
Users can now also change the base colors in their styles.less file.

I should have created a separate PR though...

**Comment by ahmadseleem** [comment]
@hgGeorg nice Thanks!

**Comment by ZakariaRidouh** [comment]
any news about if this is going to get merged?

**Comment by Alhadis** [comment]
[Fixed in v1.7.0](https://github.com/DanBrooker/file-icons/blob/master/CHANGELOG.md#170---2016-04-02).

@DanBrooker I've made this a minor release (as opposed to a simple patch) because it's making numerous noticeable adjustments that affect a whole bunch of icons... it didn't feel right to issue it as a simple patch. Hope that's okay. =)

**Pull request closed without merging**
