### PR TITLE
Add jade rabbit icon

### PR DESCRIPTION
**Pull request by digitaldesigndj**
Hello, Great package you have here! Easy on the eyes. Visual `grep` ftw!

So the Jade Lang logo is this: http://jade-lang.com/style/jade-logo-header.svg

I attempted to use this icon, but it was a bit too busy...
jade

So I simplified it a bit to what you can find in this branch. It's just the rabbit. (and it's svg, but I can upload those here.)

jade-rabbit

Cheers!

-Taylor

### CODE REVIEW

**Comment by ckross01** [comment]
Thank you!

**Comment by Alhadis** [comment]
@digitaldesigndj : Could you please commit the modified `selection.json` file so the next contributor adding an icon doesn't overwrite your work when they add a new icon?

I trust you added this using [IcoMoon](https://icomoon.io/app/#/select), right?

@ckross01 : It might be a good idea to double-check that pull requests include an updated `selection.json` file, because if contributors don't keep it updated, icons will be lost. I *did* mention in `CONTRIBUTING.md` that the `selection.json` file needs to be kept updated too.

**Comment by ckross01** [comment]
@Alhadis thanks for the call out, I'll make sure that these are included in future prs.

**Comment by digitaldesigndj** [comment]
I've taken a look around, I'm not so sure I have the changed file handy... If I need to I can redo the patch correctly, and we can roll back this attempt

**Comment by Alhadis** [comment]
IcoMoon uses your browser's local storage to save what projects you've locally worked on, so it's possible you may be able to simply visit the site to re-export it.

**Comment by digitaldesigndj** [comment]
Thanks @Alhadis! Just what I needed.

https://github.com/DanBrooker/file-icons/pull/245

**Pull request merged**
