### PR TITLE
Update example Image

### PR DESCRIPTION
**Pull request by IanVS**
This image includes all of the current icons in the `examples` directory.

### CODE REVIEW

**Comment by IanVS** [comment]
I realize you may not want to have a huge long image like this in the readme, but it might be worth putting into a separate readme in the examples folder.  I'm happy to change that if you'd like.  Or just close this, it won't hurt my feelings.

**Comment by ckross01** [comment]
That is a huge image! But it is up to date with the current supported ones so there is value here. Might get some other opinions on how we might want to handle it in the future. Either way thanks for the pr.

//cc @DanBrooker

**Comment by DanBrooker** [comment]
A updated image is great, it's a little too large for the main readme, maybe shorten it a little

**Comment by IanVS** [comment]
I can take out some of the duplicates (for example, `3ds.mcr`, and `3ds.ms`), but I think the result will still be very large.  Perhaps a better solution is to create a new README.md inside the `examples/` directory and put this image in that document?

**Comment by ckross01** [comment]
how bad does it look if we compress the image?

I do like the idea of having an examples.md that we just reference.

**Comment by IanVS** [comment]
Compress in what way?  I ran it through tinyPNG already.  Or do you mean shrink its size?

**Comment by ckross01** [comment]
shrink its size

**Comment by Alhadis** [comment]
@ckross01 : Personally, I think it'd be better to only show a selection of icons in the main readme, and have a separate document for displaying each file icon (ordered alphabetically).

I don't believe it's pertinent to have *every* icon visible to the casual reader when they first open the package, particularly not when there're now so many icons available.

**Comment by Zorgatone** [comment]
:shipit: :+1:

**Comment by Alhadis** [comment]
@IanVS I'm closing this for now... there're simply too many icons in this package to show them all in one image (and several more have been added since this PR was filed, and many more will continue being added in future...) Sorry. :(

**Comment by IanVS** [comment]
Yeah no problem, I totally get it.  The current one is enough to give the idea.

**Pull request closed without merging**
