### PR TITLE
Add .nvmrc icon.

### PR DESCRIPTION
**Pull request by austinkelleher**

### CODE REVIEW

**Comment by Alhadis** [comment]
What's this, what does it do?

**Comment by Alhadis** [comment]
I'm asking because it might be related to Node version manager... in which case, the NodeJS icon might be more appropriate than the generic gear.

**Comment by austinkelleher** [comment]
https://github.com/creationix/nvm#nvmrc

**Comment by austinkelleher** [comment]
It is the Node version manager. We could use the Node.js icon instead. I liked the gear because it aligns with the other gears in my file pane.

**Comment by Alhadis** [comment]
Everything will align a hell of a lot nicer in v2, trust me.

**Comment by austinkelleher** [comment]
By align, I meant it looked consistent. For example:

screen shot 2016-07-14 at 8 17 19 am

**Comment by austinkelleher** [comment]
But perhaps the Node.js icon is more appropriate? What do you think>

**Comment by Alhadis** [comment]
Definitely go with the NodeJS icon. The gear icon is used a *lot*, and it's really only meant to identify config-type files that lack anything more appropriate.

**Comment by Alhadis** [comment]
Also, many of the .config rules will be made redundant in v2 anyway, which will default to using the gear icon for any unrecognised filename that starts with a full-stop. =)

**Comment by austinkelleher** [comment]
Reverted last commit and changed to `node-icon`.

**Comment by austinkelleher** [comment]
@Alhadis Thanks for the feedback.

**Pull request merged**
