### PR TITLE
Added icon for stylelint

### PR DESCRIPTION
**Pull request by r3nya**
Hi there!

I tried to add the [stylelint](http://stylelint.io/) icon. Please review my change.
Btw, this icon for `.stylelintrc` files.

PS: If I made something not correctly, please add new icon manually. :pensive: 
You can find this icon on [my gist](https://gist.github.com/r3nya/7b72bd9c84886c7b795d678fea1eb531).

Advance thanks!

### CODE REVIEW

**Comment by Alhadis** [comment]
Terrific work! 👍

**Comment by r3nya** [comment]
@Alhadis phew ... I'm very happy! 😃

**Comment by Alhadis** [comment]
It was just missing a CSS rule to apply the icon to `.stylelintrc` files (as well as a file in the `examples/` directory showing the new icon addition), but don't worry, [I've added those in](https://github.com/DanBrooker/file-icons/commit/cf041bc). =) No big deal.

**Comment by r3nya** [comment]
@Alhadis awesome! ;)

**Pull request merged**
