### PR TITLE
Adding extra file extensions

### PR DESCRIPTION
**Pull request by fusion809**
This pull request is me adding the following file extensions/names:

* `.desktop`
* `.directory`
* `.menu`
* `_service`
* `_osc`
* `.install`

### CODE REVIEW

**Comment by Alhadis** [comment]
What are these file extensions used for?

**Comment by fusion809** [comment]
`.desktop` files are desktop configuration files that serve as application launchers on Linux systems. `.directory` files are identical in their syntax to desktop configuration files, except they specify folders or directories in desktop menus for Linux systems. Both have an INI-type syntax. `.menu` files are XML files that specify the structure of application menus. `_service` files are XML service files used by Open Build Service (OBS) to download sources. `_osc` is a shell script file used by the OBS too. `.install` files are shell scripts referred to by PKGBUILDs, they perform pre-, post- and peri- install and/or remove actions for their respective Arch package. For example, here's an `.install` file for the Moksha window manager:

```
post_install() {
  update-mime-database usr/share/mime > /dev/null
  update-desktop-database -q
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
```

**Comment by Alhadis** [comment]
Are they file extensions or full filenames?

I'm just a little hesitant to add something like `_service` or `_osc` as a suffix match, as it would then affect filenames like these:
```
./notes_on_service
./how_to_service
./room_service
```

If they're matching full names only, every time, it's probably better not to treat them as extensions:
```less
&[data-name="_service"]
```

**Comment by fusion809** [comment]
Yeah `_service` and `_osc` are the full names of the files, not their extensions so you're right. I just didn't know how to include that name without treating them as extensions.

**Comment by Alhadis** [comment]
Looks great, thanks! :+1:

**Pull request merged**
