### PR TITLE
Adding Arch Linux file icon and adding Deb/Red Hat icons to build files

### PR DESCRIPTION
**Pull request by fusion809**
Hi,

In this pull request I am adding the Deb/Red Hat icons to their respective package build files (`control`, `rules` and `.spec`, respectively) and a new Arch Linux icon for `PKGBUILD`, `.install`, `pacman.conf`, `pamac.conf`, `yaourtrc` and `.SRCINFO` files. 

Thanks for your time,
Brenton

### CODE REVIEW

**Comment by Alhadis** [comment]
An icon for Arch Linux actually [already exists in the Mfizz font](http://fizzed.com/oss/font-mfizz/icon-archlinux).

**Comment by Alhadis** [comment]
Could you revert your changes, save for the ones made to `file-icons.less`?

**Comment by fusion809** [comment]
What about the one I made to icons.less? Where I defined the `arch-icons` class?

**Comment by fusion809** [comment]
I think I just did what ya asked for.

**Comment by Alhadis** [comment]
Sigh... I'm actually not sure what to do now. I only just noticed the version of MFizz bundled with the package doesn't contain the Arch Linux icon (which must've been added in a newer version), and we can't upgrade [because reasons](https://github.com/DanBrooker/file-icons/pull/377).

I hate this situation.

**Comment by Alhadis** [comment]
Okay, here's what we'll do. Since Mfizz don't give a frigging damn about maintaining consistent codepoints, we can go ahead and use whichever ones we like. Re-add the Arch Linux icon:

```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 19.2.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="512px" height="512px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<path d="M186.5749664,162.1522217c18.1462555,15.3119202,47.4286499,31.2741089,72.8443756,41.2323303
	c-21.8627777-15.8652802-43.6183624-33.7482147-65.3347321-57.154892
	c18.0764465-38.5456619,39.6597595-91.7860489,61.9125214-146.1313171
	c36.2790833,92.6975708,103.8991699,232.2012177,194.4854431,397.7175293
	c-24.6089478-13.5125732-46.9073181-21.2070618-69.9294128-27.1514282
	c7.6297302,4.355011,25.6652222,14.1963806,37.2369995,22.1072998
	c18.2805481,12.4972839,35.1973572,26.1633911,51.106781,39.2492065
	C483.0965576,458.1317749,497.471283,484.7801514,512,511.9016418c-72.2558289-41.8372192-142.4728088-75.7279663-200-86.1953125
	c18.8333435-104.471344-54.8805847-166.1076355-96.760025-99.6094055
	c-16.1255188,25.6020813-20.4871674,67.7855835-12.8402405,99.1325684
	C129.6666718,439.2349854,58.5026627,478.4394836,0,511.9016418
	C68.1430206,388.4253845,137.0383453,263.2532959,186.5749664,162.1522217z"/>
</svg>
```
I suggest you use that one, because the [Mfizz one](https://github.com/fizzed/font-mfizz/blob/master/src/svg/archlinux.svg) has the same path repeated eight times for some reason:
Figure 1

Then when v2 drops, I can remove the icon from said font and transfer it to the Mfixx font using the same codepoint. Pain in the arse, but hey.

**Comment by Alhadis** [comment]
@fusion809 I've updated `icons.less` and the icon-font with an icon for Arch Linux. Feel free to do a fresh pull and update your branch. I've left it to you to do the honours.

**Comment by Alhadis** [comment]
@fusion809 Apologies, I wasn't notified that you'd made changes to the PR; I would've merged had I known.

There've since been changes to upstream (again), would you mind updating and letting me know when you've done so, please?

Also, just an FYI: `[data-name$="control"]` will match any file whose name ends in "control" (e.g., `self-control`, `Flow control`, etc). You'll want to change the [Debian additions](https://github.com/DanBrooker/file-icons/pull/382/files#diff-3902273e10e8a55db46c1b161e44217cR407) to just use `[data-name="control"]` instead (which performs a strict match against the entire name).

**Comment by fusion809** [comment]
Done.

**Comment by Alhadis** [comment]
Cheers!

**Pull request merged**
