### PR TITLE
V2: Merry Commit-Mass and a happier new year

### PR DESCRIPTION
**Pull request by Alhadis**
Let's start the new year with a bang. A hashbang.

Test thoroughly, people:

```sh
cd /your/project/folder
git clone https://github.com/DanBrooker/file-icons.git
cd file-icons
git checkout v2-staged
apm install .
apm link -d .
atom -d .
```

Don't forget to run package specs.

### CODE REVIEW

**Comment by Alhadis** [comment]
@DanBrooker I'll update the readme later, probably as we're finished with testing. Kinda exhausted ATM.

**Comment by Alhadis** [comment]
@50Wliu I swear I was kidding when I said I'd finish File-Icons V2 before my [CSS PR](https://github.com/atom/language-css/pull/99) was merged. Honest.

BTW, would appreciate a review of this too, although it shouldn't take as long. ;)

**Comment by DanBrooker** [comment]
👍 @Alhadis will have a look when I have a spare moment

**Comment by DanBrooker** [comment]
I had some custom icons in the atom stylesheet, caused interesting results
screen shot 2016-12-28 at 8 06 26 pm
Commenting out the @import's fixed it, might be worth mentioning or having the old imports empty.

How do I specify an icon for say `.amp.erb`

**Comment by Alhadis** [comment]
Hahah, you'll need to restart, mate. :) The CSS rules from the other branch are still active in the workspace.

Well, to change the icon for a file based on its path, you'd do as you'd normally do: an attribute selector:

```css
.file > [data-name="CONTRIBUTING.md"]:before{
	content: "\ea1b";
	font-family: file-icons;
}
```

Hrm, I should probably make it so users could define their own icons using the same config format the package uses...

**Comment by Alhadis** [comment]
Talk about timing of replies, haha. Thanks!

Yep, wording and rewording some stuff now. =)

**Comment by Alhadis** [comment]
This package has precisely 666 file icons, not counting those of Octicons or FontAwesome:

* [DevOpicons](https://github.com/Alhadis/DevOpicons/blob/master/charmap.md): 192 icons
* [MFixx](https://github.com/Alhadis/MFixx/blob/master/charmap.md): 108 icons
* [Our custom font](https://github.com/Alhadis/FileIcons/blob/master/charmap.md): 366 icons

```js
192 + 108 + 366 = 666
```

Metal as fucking shit.

**Comment by Alhadis** [comment]
@DanBrooker [How's this?](https://github.com/DanBrooker/file-icons/tree/v2-staged) =)

**Comment by Alhadis** [comment]
Hope that's a yes...

**Comment by DanBrooker** [comment]
All good mate. 😄

**Comment by DanBrooker** [comment]
After your epic v2, I wonder if we should move to a file-icons org, it's hardly the little project I started anymore.

**Comment by DanBrooker** [comment]
The new readme image is excellent btw

**Comment by Alhadis** [comment]
Haha, thanks. ^^ But we [gotta get Nuclide sorted first](https://github.com/DanBrooker/file-icons/issues/471#issuecomment-269659729). The damn thing replaces Atom's packages with its own - and theirs aren't even using the File-Icon API:

Ugh

Not gonna be much elegance involved with fixing this...

**Comment by 50Wliu** [comment]
Looks awesome @Alhadis.  Was on vacation so I didn't see this until now, but now that I'm back I'm planning on finishing up the CSS PR tonight or over the weekend.

**Pull request merged**
