### PR TITLE
Adding icons for CSV and TSV files

### PR DESCRIPTION
**Pull request by dan-c-underwood**

### CODE REVIEW

**Comment by astephenb** [comment]
This looks good. Can you add example files as well?

**Comment by dan-c-underwood** [comment]
Sure, I can add examples for other file types that I've added in in the past as well (unless you want that in a separate pull request?)

**Comment by astephenb** [comment]
What ever works best for you.

**Comment by dan-c-underwood** [comment]
Example files added! :smile:

**Comment by astephenb** [comment]
awesome. thanks.

**Pull request merged**
