### PR TITLE
Add support for SaltStack (.sls) and Matlab (.m)

### PR DESCRIPTION
**Pull request by natalie-**
SaltStack and Matlab icons added to ```file-icons.woff```

Matlab support can be turned on by changing ```file-icons.less```
 - Comment out Objective-C .m files (line 290)
 - Uncomment lines 438-439 for Matlab/Octave .m files

As Objective-C is more popular than Matlab, I left the Matlab lines commented out by default.

### CODE REVIEW

**Comment by ckross01** [comment]
Thanks for the pull request!

Sorry I am unfamiliar with Matlab file extension types. Is .mat a common one? If so could we leave that uncommented since I don't believe there is a conflict?

Not sure how we want to handle both matlab and object c having the .m file types. //cc @DanBrooker

**Comment by natalie-** [comment]
For matlab, .m is the most common type.  It's used for both functions and scripts.  A .mat is just used to store data.

I'd tried to be able to tell matlab scripts and objective-c .m files apart using mime type, but hadn't been able to figure it out.  I figure I'd leave it commented out and if you use matlab, uncomment it.

//cc @DanBrooker

**Comment by DanBrooker** [comment]
The css uses the file name to determine which icon to use.

I think it would be possible to add a setting to enable matlab and override the objc icon. Or just have the snippet of code available for people to add to their own user stylesheets.

**Comment by Alhadis** [comment]
Has this been merged into upstream yet?

If not, it'll raise a conflict with a PR I [just submitted earlier](https://github.com/DanBrooker/file-icons/pull/236). Paging @DanBrooker just in case I should amend my earlier work.

**Comment by Alhadis** [comment]
SaltStack resolved. See #274 .

**Pull request closed without merging**
