### PR TITLE
Adding .config and .emacs.d folders, adding Manifest to Gentoo filetypes

### PR DESCRIPTION
**Pull request by fusion809**
Hi,

In this commit I am adding the `config-icon` to `.config` folders. I also am adding the emacs icon to folders with the name `.emacs.d`. I lastly added the file name `Manifest` to the Gentoo filetype. 

Thanks for your time,
Brenton

### CODE REVIEW

**Comment by Alhadis** [comment]
This is getting a bit much. We try to be conservative with folder-icons, because it's too easy to mistake them as files if there're too many folders with unique icons. As for Manifest, I'm worried the name is too generic...

You know the theme *is* designed to have custom filetypes added in your stylesheet, right...?

**Comment by fusion809** [comment]
OK, well I suppose I could add some lines to my `~/.atom/styles.less`, it's just I thought at least the `~/.emacs.d` addition would be helpful, after all if someone has emacs installed they're likely to also have a `~/.emacs.d` folder containing config files in it.

**Comment by Alhadis** [comment]
[I do](https://github.com/Alhadis/.files), and I use Emacs as my command-line editor (with Git, etc). So I hear what you're saying. Thing is, as another user, I'm inclined to see the Emacs icon as being related to Emacs Lisp files, rather than an Emacs-related folder. This is the kind of thing that's better suited to personal configuration rather than a global addition imposed upon all users.

**Comment by fusion809** [comment]
OK. Fair enough. Shall keep this in mind in future.

**Comment by Alhadis** [comment]
I'm not trying to shoot down your willingness to contribute (and I hope you're not disheartened, because we DO appreciate your help), but understand we shouldn't be adding every potential addition for users.

Thank you for your understanding. =)

**Pull request closed without merging**
