### PR TITLE
Add in support for more Node, Python and Ruby files

### PR DESCRIPTION
**Pull request by jamieconnolly**
- Adjusted size/alignment of the Python icon (current one is too small)
- Added in quite a few icon listings for Node, Python and Ruby files

### CODE REVIEW

**Comment by Alhadis** [comment]
Don't get too carried away with the size adjustments. They're getting revamped in V2 anyway.

I believe `.python-version` is already assigned a gear icon instead of a Python one, since it represents configuration rather than Python code. As for `.node-version`, well, shouldn't that be using the `NodeJS` icon rather than the NPM logo?

**Comment by jamieconnolly** [comment]
Ok, that was the only one that bugged me whenever I was working with Python files.

It was, but the `.ruby-version` file is assigned to the Ruby icon so I just copied that precedent. Do you think all of these `*-version` files should use the gear icon, or should they use their individual language icon? If it's the latter, I completely agree on the `.node-version` using the NodeJS icon.

**Comment by Alhadis** [comment]
Hrm, the latter, I suppose.

**Comment by jamieconnolly** [comment]
Ok, I've updated the `.node-version` to use the NodeJS icon, and updated the CHANGELOG accordingly. Thanks for your guidance 👍

**Comment by Alhadis** [comment]
Still felt [this](https://github.com/DanBrooker/file-icons/issues/199#issuecomment-212499778) would've been a better solution, BTW.

**Pull request merged**
