### PR TITLE
add .tsx icon

### PR DESCRIPTION
**Pull request by mrpatiwi**
I just want a `.tsx` file icon.
Color may change, but i think `dark-blue` is ok.

image

### CODE REVIEW

**Comment by ckross01** [comment]
Thanks for the PR!

Did you think the dark-blue looked better? I guess I would expect my icon for .jsx and .tsx would be the same shade and then I can override if needed. Wondering if medium-blue might be better for consistency.

**Comment by mrpatiwi** [comment]
`jsx` uses `medium-blue`. Both would look:
image


### Other options:

with `light-blue`:
image


`medium-cyan`:
image

`light-cyan`:
image

**Comment by mrpatiwi** [comment]
I just added `.ts` and `.tsx` example files.

**Comment by ckross01** [comment]
ok not familiar with .tsx but you would want different shades because it is likely that you have folders with both .jsx and .tsx files?

**Comment by mrpatiwi** [comment]
Yes, you can work with `.js`, `.jsx`, `.ts` and `.tsx` files on the same project and folder.

**Comment by ckross01** [comment]
awesome, sounds great.

**Comment by roman01la** [comment]
Hello. I'm the author of `jsx` icon. Do you want me to add some `T` or something for better distinction? :)

**Comment by ckross01** [comment]
I think it would be nice to have a distinction that isn't just a slightly different shade of blue. That being said I dont have this file type in my project so I am not sure others who do agree with that. 

Maybe open another issue and propose something?

**Comment by mrpatiwi** [comment]
We can also change the Typescript icon. Now is just the Javascript icon in purple shade.

**Pull request merged**
