### PR TITLE
Adding Ubuntu icons for Snappy package files

### PR DESCRIPTION
**Pull request by fusion809**
Hi,

In this commit I am adding Ubuntu icons and using them for Snappy package files (namely snapcraft.yaml and .snap files). 

Thanks for your time,
Brenton

### CODE REVIEW

**Comment by Alhadis** [comment]
No such thing as `snapcraft.yml`? Or should we cater for that possible file extension too?

**Comment by fusion809** [comment]
No snapcraft.yml just snapcraft.yaml, it contains the build instructions for Snappy packages, according to the official Snapcraft documentation on creating snappy packages http://snapcraft.io/create/.

**Comment by Alhadis** [comment]
Alright mate, just checking. =)

**Comment by Alhadis** [comment]
@fusion809 Just a heads up for next time: when we add support for a new icon (either from a bundled font or a completely new custom icon), it's customary to include a sample for it in `examples/`. =) If the format has different colour variations, it helps to add those too. Make sure to do so using the same file-extension, so the relationship as a single rule-group is obvious:

Figure 1

Historically, I believe this folder was used so contributors could preview how icons would look, but in v2, I'll also be using it to provide fixtures for specs. This'll ensure future additions won't change `snapcraft.yml` into a database icon, etc.

**Comment by Alhadis** [comment]
@fusion809 Sorry to page you a second time, but I want to make sure you noticed this too:

Figure 1

You must be using a newer version of Mfizz, which has rearranged each icon's codepoint (as usual).

This is another addition I have to revert and have wait until v2 can be released (as I've explained previously). Please hold off adding any more Mfizz-related icons until v2 ships, we can't keep cluttering the revision history like this.

**Pull request merged**
